# Generated by Django 4.0.5 on 2022-06-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBaseInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50, verbose_name='学生名称')),
                ('stu_no', models.CharField(max_length=50, unique=True, verbose_name='学生编号')),
            ],
            options={
                'db_table': 'student_base_info',
            },
        ),
        migrations.CreateModel(
            name='StudentCheckInfo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, '未出现'), (2, '签到'), (3, '离开')], default=1, verbose_name='学生行为种类')),
                ('mode', models.IntegerField(choices=[(1, '旷课'), (2, '迟到'), (3, '早退'), (4, '正常')], default=1, verbose_name='学生出席状态')),
                ('is_deleted', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('stu_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_info.studentbaseinfo', to_field='stu_no', verbose_name='学生编号')),
            ],
            options={
                'db_table': 'student_check_info',
            },
        ),
    ]
