# Generated by Django 4.0.5 on 2022-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0002_mypicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_no', models.CharField(max_length=50, unique=True, verbose_name='学生编号')),
                ('picture', models.CharField(max_length=128, verbose_name='picture')),
            ],
            options={
                'db_table': 'student_image_info',
            },
        ),
        migrations.DeleteModel(
            name='mypicture',
        ),
        migrations.AddField(
            model_name='studentbaseinfo',
            name='class_no',
            field=models.IntegerField(default=-1, verbose_name='学生班级号'),
        ),
        migrations.AddField(
            model_name='studentbaseinfo',
            name='grade_no',
            field=models.IntegerField(default=-1, verbose_name='学生年级号'),
        ),
    ]
